# - name: Create an instance
#   hosts: localhost
#   gather_facts: no
#   vars:
#       gcp_project: lt-2021-001
#       gcp_cred_kind: serviceaccount
#       gcp_cred_file: /home/lahiruka_wijesinghe/lt-2021-001-b11bdda40363.json
#       zone: "asia-south1-c"
#       region: "asia-south1"

#   tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ item.disk }}"
         size_gb: 30
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: "{{ item.address }}"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "{{ item.name }}"
         machine_type: e2-medium
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         metadata:
             startup-script: |
                #!/bin/bash
                sudo apt-get install apache2 -y
                sudo echo "HELLO $HOSTNAME" > /var/www/html/index.html
                sudo systemctl restart apache2
                sudo systemctl enable apache2 
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances

   - name: Show host details
     debug: 
      msg: "Instance IP is {{ address.address }}"

